POST http://localhost:8000/api/groups/5/checkIn
Authorization: Bearer 10|YzzvXY0nFneR0FnUS6dyVfsOtLM7piybQbTSKyTI5aa1321d
Content-Type: application/json
Accept: application/json

{
    "files": [
        {
            "file_id": 49,
            "version": 6
        }
    ]
}